### ISSUE TITLE
Doge Artefacts Appearing On Screen

### ISSUE THREAD

**Issue by harry-clarke** [xxyy/xxyy.github.com#1]
When the user spends too long on this page, screen artefacts manifest themselves as text, assuring one that the site is "9001% enkrin", "many gray", and "such physix". These can only be the works of the deranged lunatic known as Doge.
To prevent the outbreak of such doge, and many grammar fail, it is probably best that you fix this bug immediately by replacing this profanity with pictures of Nicholas Cage's award-winning smile, the words "because I'm Batman!", and Her Majesty, The Queen's royal, and very personal collection of Pokemon; she is, after all, the only one to have ever 'caught them all'.

P.S. I should be dreaming right now, but I'm awake and the keyboard is right in front of me, so yeah...

P.S.S. To get you started, I have attached a picture of Nicholas Cage's award-winning smile; it's truly a site to behold.
![tumblr_mht6cnc9v81s58xsso1_500](https://cloud.githubusercontent.com/assets/5561231/5791383/1c1a9dea-9ecb-11e4-93de-6906fd53baea.jpg)

**Comment by literalplus** [comment]
It's actually "9001% enkrip"

I see where you're coming from, but remember that doge is love, doge is life - As additional proof, I have attached an image:

![Doge - Follow Your Dreams](https://cloud.githubusercontent.com/assets/547070/5794026/30bf6fdc-9f5c-11e4-9ca1-4b00906e3148.png)
