### ISSUE TITLE
Broken Contact section

### ISSUE THREAD

**Issue by 0x5ECF4ULT** [xxyy/xxyy.github.com#3]
Hey xxyy!

Offensichtlich ist die "Where to find me"-Sektion dezent hinnig. Ich kann nämlich keine Icons sehen die man anklicken könnte.
Firefox version: 65.0.1

Grüße,
tacticalDevC (Der Dude dem du in Purkersdorf mal ein Plugin [mit Tränken] programmiert hast)

**Comment by literalplus** [comment]
Hi, thanks for reporting this issue! Sadly I'm unable to reproduce it on Firefox 65.0.1:

![2019-02-25_23 02 52](https://user-images.githubusercontent.com/547070/53373582-1bed0680-3956-11e9-9372-27bad9d214da.png)

Might be an extension blocking them, e.g. an ad blocker. Consider trying in a Private Tab.

**Comment by 0x5ECF4ULT** [comment]
Update: I'm sorry you are right. It has been my adblocker blocking the icons. Closing this
